<?php
// $Id$

/**
 * Implements hook_init().
 *
 * @todo Come up with smarter inclusion of CSS/JS. Including on the
 * hook_context_links_alter() level won't work as it is too late in the page
 * build.
 */
function simpleshare_init() {
  drupal_add_js(drupal_get_path('module', 'simpleshare') . '/simpleshare.js');
  drupal_add_css(drupal_get_path('module', 'simpleshare') . '/simpleshare.css');
}

/**
 * Implements hook_help().
 */
function simpleshare_help($path, $arg) {
  if ($path == 'admin/config/system/simpleshare') {
    return t('Choose share methods that should be available to users. For actually showing a share link, configure workflow settings of content types or use Views to add a "Simple Share link" field to your listing.');
  }
}

/**
 * Implements hook_menu().
 */
function simpleshare_menu() {
  $items = array();
  $items['simpleshare'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'simpleshare_service_links',
    'page arguments' => array(),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );
  $items['admin/config/system/simpleshare'] = array(
    'title' => 'Simpleshare',
    'description' => 'Control simpleshare sharing methods.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simpleshare_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'simpleshare.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_views_api().
 */
function simpleshare_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'simpleshare') . '/views',
  );
}

/**
 * Implements hook_form_alter().
 */
function simpleshare_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'node_type_form') {
    $form['workflow']['simpleshare_enabled'] = array(
      '#type' => 'radios',
      '#title' => t('Simple Share'),
      '#description' => t('If checked, offers Share link on full node views. Choose which share methods to expose on the !settings_form.', array('!admin_form' => l(t('Simple Share settings form'), 'admin/config/system/simpleshare'))),
      '#options' => array(0 => t('Disabled'), 1 => t('Enabled')),
      '#default_value' => variable_get('simpleshare_enabled_' . $form['#node_type']->type, 0),
    );
  }
}

/**
 * Implements hook_node_view().
 */
function simpleshare_node_view($node, $view_mode) {
  if (variable_get('simpleshare_enabled_' . $node->type, 0)) {
    $node->content['links']['#links']['simpleshare'] = array(
      'title' => t('Share'),
      'href' => "node/{$node->nid}",
      'absolute' => TRUE,
      'attributes' => array(
        'title' => check_plain($node->title),
      ),
    );
  }
}

/**
 * Implements hook_context_link_alter().
 */
function simpleshare_context_links_alter(&$links) {
  if ($plugin = context_get_plugin('reaction', 'simpleshare_link')) {
    $plugin->execute($links);
  }
}

/**
 * Implements hook_ctools_plugin_plugins().
 */
function simpleshare_ctools_plugin_plugins() {
  return array(
    'cache' => TRUE,
    'use hooks' => TRUE,
  );
}

/**
 * Implements hook_context_plugins().
 */
function simpleshare_context_plugins() {
  $plugins = array();
  $plugins['simpleshare_reaction_link'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'simpleshare'),
      'file' => 'simpleshare_reaction_link.inc',
      'class' => 'simpleshare_reaction_link',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function simpleshare_context_registry() {
  return array(
    'reactions' => array(
      'simpleshare_link' => array(
        'title' => t('Simple share link'),
        'description' => t('Show a simple share link.'),
        'plugin' => 'simpleshare_reaction_link',
      ),
    ),
  );
}

/**
 * AJAX callback for generating service links.
 */
function simpleshare_service_links() {
  if (isset($_GET['url'], $_GET['title']) &&
     (_simpleshare_local_url($_GET['url']) || variable_get('simpleshare_non_local_url', FALSE))) {
    $title = check_plain($_GET['title']);
    $url = check_url($_GET['url']);

    $methods = variable_get('simpleshare_methods', simpleshare_methods());
    $urls = array();
    foreach ($methods as $key => $val) {
      if ($val) {
        $urls[$key] = $url;
      }
    }
    drupal_alter('simpleshare_service_urls', $urls);

    $links = array();
    if ($methods['twitter']) {
      $url = $urls['twitter'];
      $short_url = _simpleshare_short_url($url);
      $full_short = "{$title} ({$short_url})";

      $links['links']['twitter'] = array(
        'title' => t('Twitter'),
        'href' => 'http://twitter.com',
        'query' => array(
          'status' => $full_short,
        ),
        'attributes' => array('target' => '_blank'),
      );
    }
    if ($methods['facebook']) {
      $url = $urls['facebook'];

      $links['links']['facebook'] = array(
        'title' => t('Facebook'),
        'href' => 'http://facebook.com/share.php',
        'query' => array(
          'u' => $url,
        ),
        'attributes' => array('target' => '_blank'),
      );
    }
    if ($methods['myspace']) {
      $url = $urls['myspace'];
      $full = "{$title} ({$url})";

      $links['links']['myspace'] = array(
        'title' => t('MySpace'),
        'href' => 'http://www.myspace.com/index.cfm',
        'query' => array(
          'fuseaction' => 'postto',
          't' => $title,
          'c' => $full,
          'u' => $url,
        ),
        'attributes' => array('target' => '_blank'),
      );
    }
    if ($methods['delicious']) {
      $url = $urls['delicious'];

      $links['links']['delicious'] = array(
        'title' => t('Delicious'),
        'href' => 'http://delicious.com/save',
        'query' => array(
          'v' => '5',
          'noui' => NULL,
          'jump' => 'close',
          'url' => $url,
          'title' => $title,
        ),
        'attributes' => array('target' => '_blank'),
      );
    }
    if ($methods['email']) {
      $url = $urls['email'];
      $full = "{$title} ({$url})";

      $links['links']['email'] = array(
        'title' => t('E-mail'),
        'href' => 'mailto:',
        'query' => array(
          'subject' => $title,
          'body' => $full,
        ),
        'attributes' => array('target' => '_blank'),
      );
    }
    drupal_alter('simpleshare_service_links', $links);
    print theme('simpleshare_popup', $links, $html);
  }
  exit;
}

/**
 * Enumerate all available methods.
 *
 * Use variable_get('simpleshare_methods', array_keys(simpleshare_methods())) to
 * get the keys of all enabled methods.
 */
function simpleshare_methods() {
  return array(
    'email' => t('Email'),
    'delicious' => t('Delicious'),
    'facebook' => t('Facebook'),
    'twitter' => t('Twitter'),
    'myspace' => t('MySpace'),
  );
}

/**
 * Push URL through a URL shortening service.
 */
function _simpleshare_short_url($url, $reset = FALSE) {
  static $short_urls = array();
  if ($short_urls[$url] && !$reset) {
    return $short_urls[$url];
  }
  // @TODO make this configurable
  // $api = "http://is.gd/api.php?longurl={$url}";
  $api = "http://tinyurl.com/api-create.php?url={$url}";

  if (function_exists('curl_init')) {
    $session = curl_init();
    curl_setopt($session, CURLOPT_URL, $api);
    curl_setopt($session, CURLOPT_RETURNTRANSFER, 1);
    $short_urls[$url] = curl_exec($session);
    curl_close($session);
  }
  return $short_urls[$url];
}

/**
 * Make sure URL is a local URL.
 */
function _simpleshare_local_url($url) {
  return ($_SERVER['HTTP_HOST'] == parse_url($url, PHP_URL_HOST));
}

/**
 * Implements hook_theme().
 */
function simpleshare_theme() {
  return array('simpleshare_popup' => array());
}

/**
 * Theme a share popup box.
 */
function theme_simpleshare_popup($service_links, $text = 'Share') {
  $output = "<div class='simpleshare-popup clear-block'>";
  $output .= "<span class='close'>" . t('Close') . "</span>";
  $output .= theme('links', array('links' => $service_links['links'], 'heading' => t($text)));
  $output .= "</div>";
  return $output;
}
